services:
  db:
    image: postgres:17-alpine
    container_name: catfoodstore_postgres
    env_file:
      - ./catfoodstore_db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./catfoodstore_db/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    restart: unless-stopped

  backend:
    build:
      context: ./catfoodstore_backend
      dockerfile: Dockerfile
    container_name: catfoodstore_backend
    env_file:
      - ./catfoodstore_backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./catfoodstore-app
    container_name: catfoodstore_frontend
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: catfoodstore_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./catfoodstore-app/build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: catfoodstore_pgadmin
    env_file:
      - ./catfoodstore_db/.env
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
